services:
  api:
    build: ./api
    env_file:
      - .env
    environment:
      - PORT=2032
      - DB_PATH=/usr/src/config/prices.db
    volumes:
      - ./config:/usr/src/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2032/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "2033:2033"
    depends_on:
      - api
